### PR TITLE
Boltr. - DEX & Yield aggregator platform (Latest)

### PR DESCRIPTION
**Pull request by liamboltr**
Hello,

This is the latest boltrswap.md file .

-DEX
-Yield Aggregator Platform
-Staking Pool
-IFO
-Blockchain Summit South East Asia

### CODE REVIEW

**Comment by liamboltr** [comment]
Please refer to the latest commit changes. Sorry for making it very crowded in here because we are in meeting for filling the form that's there is changes in commit after meeting.

Regards,
Liam Kwek Seng

**Comment by boltrswap** [comment]
Boltr.
logo png


Website : https://www.boltrswap.com
Twitter : https://www.twitter.com/boltrswap
Telegram : https://t.me/boltrswap | https://t.me/boltrprotocol
Channel : https://t.me/boltrhub
Medium :https://boltr.medium.com

**Comment by boltrswap** [comment]
We give approval to the students of Universiti Teknologi Mara (MARA Technology University) UiTM, Malaysia to use our platform for their Entrepreneurship subject's assignment. In the future, we will collaborate with the University Senate for Blockchain talks about Decentralize Finance.

[Universiti Teknologi Mara - ENT.pdf](https://github.com/kcc-community/kcc-grants/files/6849618/Universiti.Teknologi.Mara.-.ENT.pdf)

**Comment by lingyun92** [comment]
Developers who applied for the program should provide their KuCoin UID in their PR, and KCC will contact them via the email address linked with the UID.

**Comment by liamboltr** [comment]
Hello Mr Leandre,Noted on that. Thank you for the informations.---- On Sun, 08 Aug 2021 21:08:54 -0700  ***@***.******@***.***> wrote ---- 
Developers who applied for the program should provide their KuCoin UID in their PR, and KCC will contact them via the email address linked with the UID.

**Comment by boltrswap** [comment]
Representative Dev UID in KuCoin: 34616062

**Comment by lingyun92** [comment]
> Representative Dev UID in KuCoin: 34616062

need liamboltr to reply

**Comment by liamboltr** [comment]
Dear Mr. Leandre,

This is my UID in KuCoin: 34616062

Thank you.

**Pull request merged**
