### PR TITLE
paprprintr.finance Grant Participation

### PR DESCRIPTION
**Pull request by PaprPrintr**

### CODE REVIEW

**Comment by Elpedrorf** [comment]
Perfecto

**Comment by lingyun92** [comment]
Developers who applied for the program should provide their KuCoin UID in their PR, and KCC will contact them via the email address linked with the UID.

**Comment by gabi0810** [comment]
Let's go !!

**Comment by iambluedev1** [comment]
> Developers who applied for the program should provide their KuCoin UID in their PR, and KCC will contact them via the email address linked with the UID.

added 👍

**Comment by lingyun92** [comment]
need @PaprPrintr to reply

**Comment by PaprPrintr** [comment]
@lingyun92 Updated

**Pull request merged**
