### PR TITLE
KCC Scan Application Proposal

### PR DESCRIPTION
**Pull request by st0ianmarius**

### CODE REVIEW

**Comment by lingyun92** [comment]
I think the roadmap or functions is not enough, maybe we can compare the functions with etherscan, make it bigger.

**Comment by st0ianmarius** [comment]
Of course, we can make it more detailed in technical terms.
Maybe split the milestones into more smaller parts this way the initial/follow-up grants are of smaller value and you can see the actual product faster.

I'll start creating a more detailed milestone section.

**Comment by lingyun92** [comment]
Developers who applied for the program should provide their KuCoin UID in their PR, and KCC will contact them via the email address linked with the UID.

**Comment by st0ianmarius** [comment]
KuCoin UID: 29203738

**Pull request merged**
